# 11_google_config.yaml
title: google_config
hl_start_browser:
  name: chrome
  options:
    - "--headless"
    - "--disable-gpu"
  start_url: "google.com"
  window_size:
    width: 1920
    height: 1080
actions:
  - type: hl_wait
    seconds: 5
  - type: hl_write
    # target: "search_box"
    target: ""
    text: "helium selenium github"
  - type: hl_press
    key: "ENTER"
  - type: hl_wait
    seconds: 5
hl_end_action: get_screen
